name: murmur
description: "Murmur — приложение для успокоения, сна и работы с эмоциональным состоянием."
publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  #other  
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  intl: ^0.20.2
  flutter_material_symbols: ^0.0.4
  email_validator: ^3.0.0
  path_provider: ^2.1.5
  shared_preferences: ^2.3.3
  sign_in_with_apple: ^7.0.1

  #firebase
  firebase_core: ^3.13.1
  cloud_firestore: ^5.6.8
  firebase_analytics: ^11.4.6
  firebase_auth: ^5.5.4
  google_sign_in: ^6.3.0
  firebase_storage: ^12.4.7
  fl_chart: ^0.71.0

  #audio
  just_audio: ^0.9.42
  audio_service: ^0.18.15
  audio_session: ^0.1.25

  #image
  image_picker: ^1.1.2
  image_cropper: ^9.1.0
  cached_network_image: ^3.4.1
  url_launcher: ^6.3.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/logo/
    - assets/audio/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/logo.png"
  min_sdk_android: 23
