// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAh7Cx5FZdYDw3qwVtNROo4_6ZtYUEmBoY',
    appId: '1:299353196169:web:c441e25eb5d90e6a172858',
    messagingSenderId: '299353196169',
    projectId: 'self-screen-1de5f',
    authDomain: 'self-screen-1de5f.firebaseapp.com',
    storageBucket: 'self-screen-1de5f.firebasestorage.app',
    measurementId: 'G-K8GP1M7XWH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuo45fdGIJaxdGhRAmbgNaf-jJ8As1ypI',
    appId: '1:299353196169:android:92cfd5b04e7737b4172858',
    messagingSenderId: '299353196169',
    projectId: 'self-screen-1de5f',
    storageBucket: 'self-screen-1de5f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDglC4Rqa92IuLuEgIm5qT4kjq_MESyhVY',
    appId: '1:299353196169:ios:a664eb503ddf4243172858',
    messagingSenderId: '299353196169',
    projectId: 'self-screen-1de5f',
    storageBucket: 'self-screen-1de5f.firebasestorage.app',
    iosBundleId: 'app.f-one.selfscreen',
  );
}
