// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'Murmur is an iOS and Android app.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBo6_7yKHYjgEgEdOqdQjyVrTaJHeWB5CE',
    appId: '1:86292750316:android:129ec7aed8ec8115a3eac9',
    messagingSenderId: '86292750316',
    projectId: 'murmur-2916d',
    storageBucket: 'murmur-2916d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDb2JtRDDoMnFePfZSeKAtAfZK1RXFhzVg',
    appId: '1:86292750316:ios:130aa8b29c23223ea3eac9',
    messagingSenderId: '86292750316',
    projectId: 'murmur-2916d',
    storageBucket: 'murmur-2916d.firebasestorage.app',
    androidClientId:
        '86292750316-33r03glu9u32k6ka2c4achkdb3durvmk.apps.googleusercontent.com',
    iosClientId:
        '86292750316-25oou270ocuhe9tat80ov6vc4t9hcqor.apps.googleusercontent.com',
    iosBundleId: 'app.f-one.murmur',
  );
}
